### ISSUE TITLE
This gem does not work with rails 4.2

### ISSUE THREAD

**Issue by NexusMTO** [jetrockets/omniauth-instagram-graph#5]
ruby 2.5.3p105 
Rails 4.2.11.1

When I install it, I run rails s, but it doesn't cause any errors but the app never starts and I don't see anything in the logs

Puma Log

[2321] Early termination of worker
[2307] Early termination of worker
[2325] Early termination of worker
.......

More

**Comment by Unstop-M** [comment]
Update:

I Close.

I use provider :instagram

And need

provider :instagram_graph
